<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Wyu2.Relay</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
    <UserSecretsId>wyu2-relay</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wyu2.Protocol\Wyu2.Protocol.csproj" />
  </ItemGroup>

</Project>
